CREATE TABLE DOCTOR_PRIMARY
( 
 DOCTOR_ID INT(10) PRIMARY KEY,
 SECURITY_QUESTIONS_ANSWER VARCHAR(50),
 ADDRESS_ID int(10) NOT NULL,
 MEDICAL_REG_ID int(10) NOT NULL UNIQUE KEY,
 EID INT(10) NOT NULL,
 SECURITY_QUESTIONS_ID int(10) NOT NULL,
 FNAME VARCHAR(50) NOT NULL,
 LNAME VARCHAR(50) NOT NULL,
 EMAIL VARCHAR(50) UNIQUE KEY NOT NULL,
 PWD VARCHAR(255) NOT NULL,
 PHONE_NUMBER CHAR(13) UNIQUE KEY NOT NULL,
 GENDER CHAR(1) NOT NULL,
 PAN_CARD CHAR(10) UNIQUE KEY NOT NULL,
 ADHAAR_CARD CHAR(12) UNIQUE KEY NOT NULL,
 SPECIALIZATION VARCHAR(50) NOT NULL,
 YEAR_OF_EXPERIENCE INT(2) NOT NULL,
 PROFILE_STATUS CHAR(1) NOT NULL DEFAULT 'U',
 PROFILE_PHOTO VARCHAR(100),
 LAST_UPDATED DATETIME DEFAULT NOW(),
 EXTRA_COL1 VARCHAR(100),
 EXTRA_COL2 VARCHAR(100),
 EXTRA_COL3 VARCHAR(100),
 CHECK (GENDER IN ('M','F','T','O')),
 CHECK (PROFILE_STATUS IN ('U','V')),

 CONSTRAINT fk_DOCTOR_ID FOREIGN KEY (DOCTOR_ID)  
 REFERENCES DOCTOR_AVAIL_MASTER(DOCTOR_ID)  
 ON DELETE CASCADE  
 ON UPDATE CASCADE,

 CONSTRAINT fk__DocPrim_ADDRESS_ID FOREIGN KEY (ADDRESS_ID)  
 REFERENCES ADDRESS(ADDRESS_ID)  
 ON DELETE CASCADE  
 ON UPDATE CASCADE,
 
 CONSTRAINT fk_MEDICAL_REG_ID FOREIGN KEY (MEDICAL_REG_ID)  
 REFERENCES DOCTOR_MED_REGISTRATION(MEDICAL_REG_ID)  
 ON DELETE CASCADE  
 ON UPDATE CASCADE,

 CONSTRAINT fk_EID FOREIGN KEY (EID)  
 REFERENCES DOCTOR_ESTABLISHMENT(EID)  
 ON DELETE CASCADE  
 ON UPDATE CASCADE,

 CONSTRAINT fk_SECURITY_QUESTIONS_ID FOREIGN KEY (SECURITY_QUESTIONS_ID)  
 REFERENCES SECURITY_QUESTIONS(SECURITY_QUESTIONS_ID)  
 ON DELETE CASCADE  
 ON UPDATE CASCADE
);