CREATE TABLE PATIENT_PRIMARY
(

UID INT(10) PRIMARY KEY AUTO_INCREMENT,

MED_RECORD_ID INT(10),

PROFILE_PHOTO VARCHAR(100),

FNAME VARCHAR(50) NOT NULL,

LNAME VARCHAR(50) NOT NULL,

EMAIL VARCHAR(100) NOT NULL UNIQUE KEY,

Pwd varchar(255) NOT NULL,

Date_of_Birth DATE NOT NULL,

ADHAAR_CARD CHAR(12) NOT NULL UNIQUE KEY,

PHONE CHAR(13) NOT NULL UNIQUE KEY,

GENDER CHAR(1) NOT NULL,

MARITAL_STATUS CHAR(1) NOT NULL,

OCCUPATION VARCHAR(100) NOT NULL,

ADDRESS_ID INT(10) UNIQUE,

SECURITY_QUESTIONS_ID INT(10) UNIQUE,

SECURITY_QUESTIONS_ANSWER VARCHAR(100),

LAST_UPDATED DATETIME DEFAULT NOW()NOT NULL, 

EXT_COL_1 VARCHAR(100) NULL,
EXT_COL_2 VARCHAR(100) NULL,
EXT_COL_3 VARCHAR(100) NULL,
CHECK (MARITAL_STATUS IN('M','U','D')),
CHECK (GENDER IN('M','F','T','O')),
CONSTRAINT fk_question_id FOREIGN KEY (SECURITY_QUESTIONS_ID) REFERENCES SECURITY_QUESTIONS(SECURITY_QUESTIONS_ID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_patient_med_record FOREIGN KEY (MED_RECORD_ID) REFERENCES PATIENT_MED_RECORD(MED_RECORD_ID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_address_id FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE PATIENT_PRIMARY AUTO_INCREMENT = 10001;

