CREATE TABLE DOCTOR_MED_REGISTRATION
(
MEDICAL_REG_NUMBER INT(10) PRIMARY KEY,
REGISTRATION_COUNCIL VARCHAR(100) NOT NULL,
REGISTRATION_YEAR YEAR NOT NULL,
DEGREE VARCHAR(20) NOT NULL,
COLLEGE VARCHAR(100) NOT NULL,
YEAR_OF_COMPLETION YEAR NOT NULL,
EXT_COL_1 VARCHAR(50),
EXT_COL_2 INT,
EXT_COL_3 CHAR(10),
LAST_UPDATED_DATE DATETIME DEFAULT NOW()
);