CREATE TABLE PATIENT_MED_LOG_TEST(
MED_LOG_ID INT(10) PRIMARY KEY,
PRESCRIPTION VARCHAR(100) NOT NULL,
LAST_UPDATED DATETIME DEFAULT NOW() NOT NULL,
UID INT(10),
EXTRA_COL1 VARCHAR(200) NULL,
EXTRA_COL2 VARCHAR(200) NULL,
EXTRA_COL3 VARCHAR(200) NULL,
);


