CREATE TABLE PATIENT_LAB_REPORT_TEST(
LAB_REPORT_ID INT(10) PRIMARY KEY,
LAB_REPORT_TYPE VARCHAR(50) NOT NULL,
LAB_REPORT VARCHAR(100) NOT NULL,
LAST_UPDATED DATETIME DEFAULT NOW() NOT NULL,
EXTRA_COL1 VARCHAR(100) NULL,
EXTRA_COL2 VARCHAR(100) NULL,
EXTRA_COL3 VARCHAR(100) NULL
);




