CREATE TABLE DOCTOR_MED_REGISTRATION_TEST
(
MEDICAL_REG_NUMBER INT(10) PRIMARY KEY,
REGISTRATION_COUNCIL VARCHAR(100),
REGISTRATION_YEAR YEAR,
DEGREE VARCHAR(20),
COLLEGE VARCHAR(100),
YEAR_OF_COMPLETION YEAR,
EXT_COL_1 VARCHAR(50),
EXT_COL_2 INT,
EXT_COL_3 CHAR(10),
LAST_UPDATED_DATE DATETIME
);