CREATE TABLE PATIENT_PRIMARY_TEST_TABLE
(
UID INT(10) PRIMARY KEY,
FNAME VARCHAR(50), 
LNAME VARCHAR(50),
PHONE CHAR(13),
GENDER CHAR(1),
ADHAAR_CARD CHAR(12),
MARITAL_STATUS CHAR(1),
EMAIL VARCHAR(100),
DOB DATE,
OCCUPATION VARCHAR(100),
ADDRESS_ID INT(10),
SECURITY_QUESTIONS_ID INT(10),
SECURITY_QUESTIONS_ANSWER VARCHAR(100),
LAST_UPDATED_DATE DATETIME DEFAULT NOW(), 
EXT_COL_1 VARCHAR(50),
EXT_COL_2 INT,
EXT_COL_3 CHAR(10)
);



