CREATE TABLE PATIENT_MED_RECORD
(
UID INT(10) PRIMARY KEY AUTO_INCREMENT,
BLOOD_PRESSURE CHAR(7) NOT NULL, 
WEIGHT CHAR(3) NOT NULL,
SUGAR_LEVEL CHAR(3) NOT NULL,
BLOOD_GROUP CHAR(3) NOT NULL,
DISABILITY CHAR(1) NOT NULL DEFAULT 'N',
LAST_UPDATED_DATE DATETIME DEFAULT NOW(), 
INSURANCE_ID VARCHAR(20) UNIQUE KEY,
INSURANCE_NAME VARCHAR(50),
INSURANCE_EXPIRE_DATE DATE,
ABHA_NUMBER CHAR(17) UNIQUE KEY,
EXT_COL_1 VARCHAR(50),
EXT_COL_2 INT,
EXT_COL_3 CHAR(10),
CHECK (DISABILITY IN ('Y','N'))
);

ALTER TABLE PATIENT_MED_RECORD AUTO_INCREMENT = 10001;
